baseURL = "https://incredible-rabanadas-c716d8.netlify.app/"
languageCode = "en-us"
paginate = 6
summarylength = 10
title = "Mary Lay | Personal Blog Test"
theme = "blogge"

[menu]
  [[menu.main]]
    name = "Home"
    url= ""
    weight= 1
  [[menu.main]]
    name = "About Me"
    url= "about"
    weight= 2
  [[menu.main]]
    name = "Contact me"
    url= "contact-me"
    weight= 3

[params]
  summarylength = 80
  logo = "images/logo.svg"
  author = "Mary Lay"
  authorThumb = "images/author.png"
  authorAddress = "Lorem 142 Str., 2352, Ipsum, State, USA"
  authorPhone = "+51-257634 534"
  instaUsername = "mary_astor"
  facebookUsername = "mary_lay"
  twitterUsername = "mary_lay"
  linkedinUsername = "mary_lay"
  blogTitle = "Articles"
  blogSubTitle = "View the latest news on Blogger"
  trendingBlogIcon = "images/blog/icon.svg"

[taxonomies]
   tag = "tags"

# Replace the third party URL/API with yours
# We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/f/mgeprrvl"
  googleMapAPI = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"